src/cli/init.rs
src/cli/watch.rs

Just style nits, clippy found no errors. :+1:

fix some clippy warnings

---

.watch.yaml
README.md
src/cli/watch.rs

feat: add ignored patterns

---

src/cli/watch.rs
src/lib.rs
src/main.rs
src/yaml.rs

feat: multiple commands for event

---

.watch.yaml
src/cli/init.rs
src/cli/watch.rs
src/main.rs
src/yaml.rs

feat: new yaml structure

---

src/cli/watch.rs
src/yaml.rs

feat: validate required keys

---

Cargo.lock

This updates to the latest compatible version of most of the dependencies.

Dependency updates

---

src/cli/watch.rs
src/cmd.rs
src/lib.rs
src/yaml.rs

Fix warnings

---

Cargo.lock
Cargo.toml
Makefile
src/cli/watch.rs
src/main.rs
src/rules.rs
tests/integration/.tests.yaml
tests/integration/functions.sh
tests/integration/runner.sh
tests/integration/specs/run-target-task-test.sh

feat: allows filtering for target task

---

.gitignore
.watch.yaml
tests/integration/functions.sh
tests/integration/runner.sh
tests/integration/specs/ignoring-folders-tests.sh

(cherry picked from commit b20bac2a3de5674789c408c464c1a1fce2b1ca93)

test: integrations show failed log

---

Cargo.lock
Cargo.toml
examples/long-task.yaml
linux-install.sh
src/cli/watch.rs
src/cli/watch_non_block.rs
src/lib.rs
src/main.rs
src/watcher.rs
tests/integration/specs/ignoring-folders-tests.sh
tests/integration/specs/watch-command-test.sh

fix: watcher doesn't work on vs-code/sublime/nano

---

src/main.rs
src/rules.rs
src/watches.rs
src/yaml.rs

fix: shows error message when config file is invalid 

---

README.md
src/main.rs

feat: load both .yaml & .yml

---

shell.nix

(cherry picked from commit 9e2be86944ce176aa929accc0b6b4e4b6e917972)

chore: adds shell nix

---

.watch.yaml
src/main.rs
src/rules.rs
src/yaml.rs

(cherry picked from commit 7723d651cdc221e79f3f1ee14fc818fba0d627c3)
The error caught in the tests was out bound index, this fixes and return the correct error

fix(tests): checks items list size and fail properly

---

.watch.yaml
README.md
examples/list-of-failing-commands.yml
src/cli/watch.rs
src/cli/watch_non_block.rs
src/main.rs
src/watcher.rs
src/workers.rs
tests/tasks_that_run_on_init.rs
tests/tasks_with_filepath_template.rs
tests/watcher_does_not_die_with_failing_tasks.rs
tests/watching_with_fail_fast_flag.rs

Fixes https://github.com/cristianoliveira/funzzy/issues/104

feat: adds `--fail-fast` flag to quit at first failure

---

examples/long-task.yaml
src/cmd.rs
src/workers.rs
tests/watching_with_fail_fast_flag.rs
tests/watching_with_non_block_flag.rs

Fixes https://github.com/cristianoliveira/funzzy/issues/136

fix(flag): '--non-block' respect task order from top-bottom

---

tests/common/macros.rs

(cherry picked from commit e746c5379c640b036f7120c546d41ea37294cc40)

tests: adds more logs to integration tests

---

.github/workflows/on-push-integration-test.yml
Makefile
examples/longtask.sh
src/workers.rs
tests/common/macros.rs
tests/tasks_with_filepath_template.rs
tests/watching_with_non_block_flag.rs

(cherry picked from commit d191ea708fea8a68f34f2ab0830755a15071de52)

fix: issue with hanging sub process after SIGINT

---

.watch.yaml
src/cli/watch.rs
src/cli/watch_non_block.rs
src/stdout.rs
tests/common/lib.rs
tests/tasks_with_filepath_template.rs
tests/watching_configured_rules.rs
tests/watching_filtered_tasks_with_target_flag.rs
tests/watching_with_non_block_flag.rs

(cherry picked from commit 306b73c5bc08272ea37b0506aa80add0268b39bf)

feat(stdout): last output without new line for smaller output

---

src/main.rs
src/rules.rs
src/yaml.rs

feat: validates all rules before start watcher

---

tests/command_init_errors.rs

(cherry picked from commit 00dab17542ff4f4d91055d6426c392583e35b2d2)

tests: makes sure to clean files before testing

---

.github/workflows/on-push-integration-test.yml
Cargo.toml
Makefile
tests/watching_configured_rules.rs

(cherry picked from commit 13e914c675ed52329115e160bcaf23df2b22de05)

tests(int): runs complete integration only on ci

---

src/cli/init.rs
src/errors.rs
src/stdout.rs
tests/command_init.rs
tests/watching_configured_errors.rs

(cherry picked from commit 9d6101860b744440dbca36bea5711873ab2cd761)

feat(init): better cli onboarding with init command

---

Cargo.lock
nix/package-local.nix

(cherry picked from commit 0b7d6446a758ef2684d8aab3b085483c760a3983)

chore: upgrade cargo dependencies

---

README.md
docs/USAGE.md

Summary:
This commit adds a thorough usage guide for Funzzy in a new USAGE.md file and includes a link to this documentation in the main README.md file.
Detailed Changes:
- README.md:
- Added a link to the new documentation under the "Want more examples?" section.
- docs/USAGE.md:
- Created a new file providing detailed usage instructions for Funzzy, including setup, configuration, available flags, and examples.

docs(usage): add comprehensive usage documentation

---

README.md
docs/USAGE.md

(cherry picked from commit 1d992c30424084f749c3352ce0aff2d31b9cac15)

docs: adds more details to usage docs
